json.extract! @track,
                      :id,
                      :user_id,
                      :title,
                      :audio,
                      :description,
                      :image,
                      :plays,
                      :genre_id,
                      :created_at,
                      :updated_at
